### ISSUE TITLE
Define  the web site template

### ISSUE THREAD

**Issue by osmanjosue** [osmanjosue/portfolioDevSite#1]

**Comment by EduardoAC** [comment]
Hi @osmanjosue, How are you getting along designing the template?

**Comment by osmanjosue** [comment]
I've done this at this moment with these points to clarify (is not finished yet):

- The page will only have two routes (welcome, contact).
- The picture is just a placeholder.
- The structure needs to receive your feedback (contact card, experience, education, technology stack).
- The colors also need your feedback.
- The 'Experience' section has 2 Accordion groups that will show up only if the user wants to. I want to avoid to much text to read at first sight. Tell me if it is ok.

![bocetoPagina](https://github.com/osmanjosue/portfolioDevSite/assets/44875165/e009574f-fcee-4854-9c5b-da3e561a1ab9)

**Comment by EduardoAC** [comment]
Wow, that looks quite good. First of all

> The page will only have two routes (welcome, contact).

What about the social and contact icons underneath if you plan to include a contact route, page, or section? Having both means having two separate contact places. If this is the intent, then go for it, but it's worth considering that it may be enough to have just the contact icons for the initial version.

Finally, I propose to start building a one pager website like, for instance, https://praveen.science/

> The picture is just a placeholder.

That's fine; I recommend a more welcoming picture with a smile, which tends to attract more engagement from the audience based on my experience. 

> The` structure needs to receive your feedback (contact card, experience, education, technology stack).

The structure looks good. I recommend moving the skills to the beginning, as it's one of the most exciting parts for someone looking at someone's CV. What do you think?

> The colours also need your feedback.

I trust and value your design skills. Could you tell me more about your decision? Why have you chosen these colours? And What will you feel is missing?

> The 'Experience' section has 2 Accordion groups that will show up only if the user wants to. I want to avoid reading too much text at first sight. Tell me if it is ok.

It's good. You have an excellent baseline to start implementing. So, could you check the feedback above, and if you are satisfied, would it be good to start building the site? We can go through it on Monday even if it's not finished.

**Comment by osmanjosue** [comment]
1. I agree, I will use the 'one-page website' style.
2. I'll take a good picture this weekend.
3. I will change the positions of skills and experience.
4. I don't want anything too colorful; I want to focus on just three colors (black, white & purple) to maintain the page's focus and not on the design (because at this point, we are interested in presenting something neutral). Purple is a color that recently has given me the sensation of not being too colorful but not boring either. The purple can be exchanged for any other color. I want to have a 'theme change button' and switch between maybe four optional colors, for example: purple (initial value), orange, red, and blue – one color at a time.

So, I will include all these observations and give you maybe the last prototype of this sketch by tomorrow. I know it will be Sunday, so don't feel any pressure from my side; we can discuss it in the Monday mentoring session.

**Comment by EduardoAC** [comment]
That sounds good; perhaps it might be worth it as it seems to go in the right direction towards implementation, possibly having some of the setup done to discuss on Monday will be valuable

**Comment by osmanjosue** [comment]
We will start with this sketch.

![Image](https://github.com/osmanjosue/portfolioDevSite/assets/44875165/b4773edf-0fb3-4bd2-bd93-560ed59069a2)

**Comment by EduardoAC** [comment]
Well done, simple, clear and straightforward to build; great work

**Comment by osmanjosue** [comment]
Hello Eduardo, you can check the web site at this point opening the index.html file that is in the dist folder in the vsCode application.

**Comment by EduardoAC** [comment]
Good morning. 

Personally, the template looks quite good. 

I suggest switching formations with experience. Recruiters will be more interested in the commercial experience than the formation. If you think about it, this is mostly the default layout that LinkedIn uses for its profiles, with the caveat of skills. 

Therefore, my suggestion in order will be
- About
- Skills
- Experience
- Formation

**Comment by osmanjosue** [comment]
fully agreed
